[tool.poetry]
name = "film-fight"
version = "0.1.0"
description = ""
authors = ["OliveRoquesUNCA <oliveroques78@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
neo4j = "^5.28.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
